/*
This file holds all the actions name
that will be used by reducers and other action files.
*/
export const SHOW_CONFIRM_MODAL_SUCCESS = "SHOW_CONFIRM_MODAL_SUCCESS";
export const HIDE_CONFIRM_MODAL_SUCCESS = "HIDE_CONFIRM_MODAL_SUCCESS";
export const BROWNBAG_NEXT_PRESENTER = "BROWNBAG_NEXT_PRESENTER";
export const BROWNBAG_NEXT_PRESENTER_SUCCESS = "BROWNBAG_NEXT_PRESENTER_SUCCESS";
export const LOAD_UNPRESENTED_USERS_SUCCESS = "LOAD_UNPRESENTED_USERS_SUCCESS";
export const RECEIVE_UNPRESENTED_USERS = "RECEIVE_UNPRESENTED_USERS";
export const REQUEST_UNPRESENTED_USERS = "REQUEST_UNPRESENTED_USERS";
export const RECEIVE_UNPRESENTED_USERS_SUCCESS = "RECEIVE_UNPRESENTED_USERS_SUCCESS";
export const REQUEST_BROWNBAG_SHUFFLE = "REQUEST_BROWNBAG_SHUFFLE";
export const RECEIVE_BROWNBAG_SHUFFLE_SUCCESS = "RECEIVE_BROWNBAG_SHUFFLE_SUCCESS";
export const CONFIRM_BROWNBAG_DONE = "CONFIRM_BROWNBAG_DONE";
export const CONFIRM_BROWNBAG_CANCEL = "CONFIRM_BROWNBAG_CANCEL";
export const BROWNBAG_ACTION_ERROR = "BROWNBAG_ACTION_ERROR";
