/* 
This file holds all the actions name 
that will be used by reducers and other action files.
*/ 
export const SHOW_CONFIRM_MODAL_SUCCESS = "SHOW_CONFIRM_MODAL_SUCCESS";
export const HIDE_CONFIRM_MODAL_SUCCESS = "HIDE_CONFIRM_MODAL_SUCCESS";
export const BROWNBAG_NEXT_INLINE = "BROWNBAG_NEXT_INLINE";
export const LOAD_UNPRESENTED_USERS_SUCCESS = "LOAD_UNPRESENTED_USERS_SUCCESS";
export const RECEIVE_UNPRESENTED_USERS = "RECEIVE_UNPRESENTED_USERS";
export const REQUEST_UNPRESENTED_USERS = "REQUEST_UNPRESENTED_USERS";
export const RECEIVE_UNPRESENTED_USERS_SUCCESS = "RECEIVE_UNPRESENTED_USERS_SUCCESS";

